# Generated by Django 2.1.3 on 2018-11-15 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='votes',
            field=models.ManyToManyField(related_name='voter', through='tickets.Vote', to='users.User'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'ticket')},
        ),
    ]
